name: TEST build GH Pages
on:
  workflow_call:
    secrets:
      GH_ACTIONS_TOKEN:
        required: true
jobs:
  create-pages:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          token: ${{ secrets.GH_ACTIONS_TOKEN }}
          submodules: true  # Fetch Hugo themes (true OR recursive)
          fetch-depth: 0    # Fetch all history for .GitInfo and .Lastmod

      - name: Modify ace-documentation shortcode template to not require a page title to be defined in YAML frontmatter
        run: sed -i 's/\.Title/\.File\.BaseFileName | humanize | title/' ${GITHUB_WORKSPACE}/themes/ace-documentation/layouts/shortcodes/childpages.html

      - name: Modify ace-documentation left navbar template to not require a page title to be defined in YAML frontmatter
        run: sed -i 's/\.LinkTitle/\.File\.BaseFileName | humanize | title/' ${GITHUB_WORKSPACE}/themes/ace-documentation/layouts/partials/menu.html
      - name: Create a directory
        run: mkdir -p "${GITHUB_WORKSPACE}/themes/ace-documentation/layouts/_default/_markup" 
        
      #- run: echo '<a href="{{ (.Page.GetPage .Destination).RelPermalink | safeURL }}">{{ .Text | safeHTML }}</a>' > ${GITHUB_WORKSPACE}/themes/ace-documentation/layouts/_default/_markup/render-link.html

      - name: Create a markdown link render hook
        run: |
          cat << EOF > ${GITHUB_WORKSPACE}/themes/ace-documentation/layouts/_default/_markup/render-link.html
          {{- \$link := .Destination }}
          {{- \$url := urls.Parse \$link }}
          {{- \$isRemote := \$url.IsAbs }}
          {{- if and (not \$isRemote) (strings.HasSuffix \$url.Path ".md") }}
            {{- \$link = relref .Page \$link }}
          {{- end -}}
          <a href="{{ \$link | safeURL }}"{{ with .Title}} title="{{ . }}"{{ end }}{{ if \$isRemote }} target="_blank"{{ end }}>{{ .Text | safeHTML }}</a>
          EOF
     
      - name: Setup Hugo
        uses: peaceiris/actions-hugo@v3
        with:
          hugo-version: 'latest'
          extended: true
          
      - name: Build
        run: hugo --minify
